import { LegalLayout, LegalSection } from "@/components/LegalLayout";

export default function PrivacyPage() { return <LegalLayout title="Privacy Policy" summary="How FormalType collects, uses, stores and gives you control over personal data.">
  <LegalSection title="What we collect"><p>When you create an account, we process your email address, account identifier, handle, profile information and avatar. When you use the service, we may store typing results, attempt details, achievements, friendships, public-profile choices and feedback.</p><p>Some preferences and anonymous practice data are stored only in your browser. Optional analytics and advertising services may collect device, usage, cookie or similar identifiers when enabled.</p></LegalSection>
  <LegalSection title="Why we use it"><p>We use data to authenticate accounts, save and analyse practice results, operate leaderboards and friend comparisons, secure the service, respond to feedback, understand product performance and—if enabled—support advertising.</p></LegalSection>
  <LegalSection title="Sharing and processors"><p>FormalType uses Supabase for authentication, database and file storage, and may use Vercel for hosting. Google Analytics and Google AdSense are optional production integrations. We do not sell your typing history or profile data.</p></LegalSection>
  <LegalSection title="Public information"><p>Your handle, enabled public profile, selected profile fields and qualifying leaderboard results may be visible to other users. Email addresses and private attempt details are not displayed publicly.</p></LegalSection>
  <LegalSection title="Retention and your choices"><p>We retain account data while your account is active or as needed to operate and protect the service. Account settings let you delete saved statistics or permanently delete your account. You can also keep your public profile private and clear local browser data.</p></LegalSection>
  <LegalSection title="Security and international processing"><p>We use access controls, row-level security and restricted service permissions. No online service can guarantee absolute security. Providers may process data outside Hong Kong subject to their contractual and technical safeguards.</p></LegalSection>
  <LegalSection title="Your rights and contact"><p>You may request access or correction and use the in-product controls for deletion. Privacy questions can be sent through the Feedback link or to feedback@formaltype.app. We may update this policy as the Beta and its providers change.</p></LegalSection>
</LegalLayout>; }
